import { ArchetypeName, ArchetypeResult } from '../types/assessment';

// All 8 archetype definitions
export const ARCHETYPES: Record<ArchetypeName, ArchetypeResult> = {
  'Perfectionist Builder': {
    name: 'Perfectionist Builder',
    description: 'You hold yourself to incredibly high standards and constantly strive for excellence. While this drives quality, it can also fuel self-doubt.',
    traits: ['Detail-oriented', 'High standards', 'Self-critical'],
    strength: 'Your commitment to quality sets you apart from competitors.',
    challenge: 'Perfectionism can slow progress and amplify imposter feelings.',
    recommendation: 'Practice shipping "good enough" versions and iterating based on real feedback rather than imagined perfection.',
    isUrgent: false,
  },
  'Opportunistic Visionary': {
    name: 'Opportunistic Visionary',
    description: 'You see possibilities everywhere and have the confidence to pursue them. Your risk tolerance and self-belief are your superpowers.',
    traits: ['Bold', 'Confident', 'Opportunity-focused'],
    strength: 'Your ability to spot and seize opportunities gives you a competitive edge.',
    challenge: 'High confidence can sometimes blind you to legitimate risks.',
    recommendation: 'Balance your optimism with input from trusted advisors who can provide grounded perspectives.',
    isUrgent: false,
  },
  'Isolated Dreamer': {
    name: 'Isolated Dreamer',
    description: 'You have big visions but tend to work alone. Your isolation may be amplifying doubts and making the journey harder than it needs to be.',
    traits: ['Independent', 'Visionary', 'Introspective'],
    strength: 'Your ability to think deeply and independently leads to unique insights.',
    challenge: 'Isolation can distort your perspective and amplify negative thoughts.',
    recommendation: 'Prioritize building connections with other founders—even one trusted peer can transform your experience.',
    isUrgent: false,
  },
  'Burning Out': {
    name: 'Burning Out',
    description: 'Multiple psychological dimensions are elevated, indicating significant stress. This is a signal to prioritize your mental health immediately.',
    traits: ['Overwhelmed', 'Stressed', 'Depleted'],
    strength: 'Your awareness of these feelings is the first step toward recovery.',
    challenge: 'Continuing at this pace risks serious burnout and health consequences.',
    recommendation: 'Please reach out to a mental health professional or trusted mentor today. Your wellbeing matters more than any startup.',
    isUrgent: true,
  },
  'Self-Assured Hustler': {
    name: 'Self-Assured Hustler',
    description: 'You have strong self-belief and low doubt. Your confidence propels you forward, though staying grounded remains important.',
    traits: ['Confident', 'Driven', 'Resilient'],
    strength: 'Your self-assurance helps you push through obstacles that stop others.',
    challenge: 'High confidence can sometimes prevent you from seeking needed help or feedback.',
    recommendation: 'Actively seek out critical feedback and diverse perspectives to complement your confidence.',
    isUrgent: false,
  },
  'Community-Driven': {
    name: 'Community-Driven',
    description: 'You thrive on connection and draw strength from your network. Your low isolation and collaborative nature are valuable assets.',
    traits: ['Connected', 'Collaborative', 'Supportive'],
    strength: 'Your network provides resilience, resources, and diverse perspectives.',
    challenge: 'You may sometimes prioritize others\' opinions over your own instincts.',
    recommendation: 'Continue nurturing your community while also developing confidence in your independent judgment.',
    isUrgent: false,
  },
  'Balanced Founder': {
    name: 'Balanced Founder',
    description: 'Your psychological profile shows healthy balance across dimensions. You have a solid foundation for the founder journey.',
    traits: ['Balanced', 'Grounded', 'Self-aware'],
    strength: 'Your equilibrium allows you to navigate challenges without extreme reactions.',
    challenge: 'Maintaining balance during high-stress periods will require intentional effort.',
    recommendation: 'Document what keeps you balanced now so you can return to these practices during tough times.',
    isUrgent: false,
  },
  'Growth Seeker': {
    name: 'Growth Seeker',
    description: 'You show a healthy mix of self-awareness and ambition. Your profile suggests openness to growth and learning.',
    traits: ['Curious', 'Adaptable', 'Growth-minded'],
    strength: 'Your willingness to learn and adapt will serve you well through startup challenges.',
    challenge: 'Growth requires consistent effort and sometimes uncomfortable self-reflection.',
    recommendation: 'Embrace the journey of continuous improvement—every challenge is an opportunity to grow.',
    isUrgent: false,
    encouragement: 'You\'re on a great path! Your openness to growth and self-awareness are exactly what successful founders need. Keep learning, stay curious, and trust the process.',
  },
};
